### ISSUE TITLE
Scaffold Functions > Failed to find "autorest". Autorest is installed, via npm.

### ISSUE THREAD

**Issue by mcquiggd** [microsoft/vscode-apimanagement#152]
Hi,

a promising extension, please keep up the good work enhancing it!

I am trying to use the Scaffold Azure Functions feature, against an API running in Azure.

I have installed autorest via NPM, and this is accessible (in both Windows, and WSL2, which I also use).

I receive the error:

Failed to find "autorest" | Extension needs AutoRest to generate a function app from an OpenAPI specification. Click "Learn more" for more details on installation steps.

I have verified that autorest is correctly installed, and is functional, including with the VS Code terminal.

Screenshot of autorest in VS Code terminal, and error autorest not found:

![image](https://user-images.githubusercontent.com/1839845/102687651-7e2c9080-41e8-11eb-97ea-e699f32fe43c.png)

**Comment by nemethmik** [comment]
Exactly the same issue, here.

**Comment by mauri84** [comment]
Hi,

Im new to the open source community so Im not sure how to create a pull request. 
But the issue is created by using the --version flag instead of the --info one. As per the --help of Autorest the --version flag is used for selecting a version of autorest/core and does not display version information.

If line **209** of the file "**src/commands/generateFunctions.ts**" is modified with the correct flag (--info) then the extension has no problem in finding autorest and generate Azure functions from the provided OpenApi file.

![Autorest_screen](https://user-images.githubusercontent.com/5490299/111848115-15d57400-88e9-11eb-9c5f-6cf85ef79665.jpg)

Thanks,
Mauricio.

**Comment by RupengLiu** [comment]
Thanks for your suggestion, will fix and improve this
